// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwapService.Domain.Models;

public partial class Battery
{
    public Guid BatteryId { get; set; }

    public string BatteryCode { get; set; }

    public Guid BatteryTypeId { get; set; }

    public Guid? StationId { get; set; }

    public string SerialNumber { get; set; }

    public DateOnly? ManufactureDate { get; set; }

    public DateOnly? PurchaseDate { get; set; }

    public string Status { get; set; }

    public int ChargeLevel { get; set; }

    public decimal SohPercentage { get; set; }

    public int TotalCycles { get; set; }

    public DateTime? LastSwapDate { get; set; }

    public DateOnly? LastMaintenanceDate { get; set; }

    public DateOnly? NextMaintenanceDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}