// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwapService.Domain.Models;

public partial class Booking
{
    public Guid BookingId { get; set; }

    public Guid DriverId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid StationId { get; set; }

    public DateTime BookingTime { get; set; }

    public DateTime ScheduledTime { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Swap> Swaps { get; set; } = new List<Swap>();
}