// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace SwapService.Domain.Models;

public partial class ev_battery_swapContext : DbContext
{
    public ev_battery_swapContext()
    {
    }

    public ev_battery_swapContext(DbContextOptions<ev_battery_swapContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Battery> Batteries { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Swap> Swaps { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Battery>(entity =>
        {
            entity.HasKey(e => e.BatteryId).HasName("pk_batteries");

            entity.ToTable("batteries");

            entity.HasIndex(e => e.BatteryTypeId, "ix_batteries_battery_type");

            entity.HasIndex(e => e.ChargeLevel, "ix_batteries_charge_level");

            entity.HasIndex(e => e.SohPercentage, "ix_batteries_soh");

            entity.HasIndex(e => e.StationId, "ix_batteries_station");

            entity.HasIndex(e => e.Status, "ix_batteries_status");

            entity.HasIndex(e => e.BatteryCode, "ux_batteries_code").IsUnique();

            entity.HasIndex(e => e.SerialNumber, "ux_batteries_serial").IsUnique();

            entity.Property(e => e.BatteryId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("battery_id");
            entity.Property(e => e.BatteryCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("battery_code");
            entity.Property(e => e.BatteryTypeId).HasColumnName("battery_type_id");
            entity.Property(e => e.ChargeLevel).HasColumnName("charge_level");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.LastMaintenanceDate).HasColumnName("last_maintenance_date");
            entity.Property(e => e.LastSwapDate).HasColumnName("last_swap_date");
            entity.Property(e => e.ManufactureDate).HasColumnName("manufacture_date");
            entity.Property(e => e.NextMaintenanceDate).HasColumnName("next_maintenance_date");
            entity.Property(e => e.PurchaseDate).HasColumnName("purchase_date");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("serial_number");
            entity.Property(e => e.SohPercentage)
                .HasDefaultValue(100.00m)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("soh_percentage");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("available")
                .HasColumnName("status");
            entity.Property(e => e.TotalCycles).HasColumnName("total_cycles");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("pk_bookings");

            entity.ToTable("bookings");

            entity.HasIndex(e => e.DriverId, "ix_bookings_driver");

            entity.HasIndex(e => e.ScheduledTime, "ix_bookings_scheduled_time");

            entity.HasIndex(e => e.StationId, "ix_bookings_station");

            entity.HasIndex(e => e.Status, "ix_bookings_status");

            entity.Property(e => e.BookingId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("booking_id");
            entity.Property(e => e.BookingTime).HasColumnName("booking_time");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.ScheduledTime).HasColumnName("scheduled_time");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("pk_payments");

            entity.ToTable("payments");

            entity.HasIndex(e => e.PaymentDate, "ix_payments_date");

            entity.HasIndex(e => e.DriverId, "ix_payments_driver");

            entity.HasIndex(e => e.PaymentStatus, "ix_payments_status");

            entity.HasIndex(e => e.PaymentType, "ix_payments_type");

            entity.Property(e => e.PaymentId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("payment_id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("payment_date");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("pending")
                .HasColumnName("payment_status");
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("payment_type");
            entity.Property(e => e.SubscriptionPlanId).HasColumnName("subscription_plan_id");
            entity.Property(e => e.SwapId).HasColumnName("swap_id");
            entity.Property(e => e.TransactionRef)
                .HasMaxLength(255)
                .HasColumnName("transaction_ref");

            entity.HasOne(d => d.Swap).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SwapId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_payments_swaps");
        });

        modelBuilder.Entity<Swap>(entity =>
        {
            entity.HasKey(e => e.SwapId).HasName("pk_swaps");

            entity.ToTable("swaps");

            entity.HasIndex(e => e.DriverId, "ix_swaps_driver");

            entity.HasIndex(e => e.StationId, "ix_swaps_station");

            entity.HasIndex(e => e.Status, "ix_swaps_status");

            entity.HasIndex(e => e.SwapStartTime, "ix_swaps_swap_time");

            entity.Property(e => e.SwapId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("swap_id");
            entity.Property(e => e.BatteryInChargeLevel).HasColumnName("battery_in_charge_level");
            entity.Property(e => e.BatteryInId).HasColumnName("battery_in_id");
            entity.Property(e => e.BatteryOutChargeLevel).HasColumnName("battery_out_charge_level");
            entity.Property(e => e.BatteryOutId).HasColumnName("battery_out_id");
            entity.Property(e => e.BookingId).HasColumnName("booking_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.OdometerReading).HasColumnName("odometer_reading");
            entity.Property(e => e.StaffId).HasColumnName("staff_id");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("in_progress")
                .HasColumnName("status");
            entity.Property(e => e.SwapEndTime).HasColumnName("swap_end_time");
            entity.Property(e => e.SwapStartTime)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("swap_start_time");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");

            entity.HasOne(d => d.Booking).WithMany(p => p.Swaps)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_swaps_bookings");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}