// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwapService.Domain.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public Guid DriverId { get; set; }

    public Guid? SwapId { get; set; }

    public Guid? SubscriptionPlanId { get; set; }

    public string PaymentType { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string TransactionRef { get; set; }

    public DateTime PaymentDate { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Swap Swap { get; set; }
}