// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwapService.Domain.Models;

public partial class Staff
{
    public Guid StaffId { get; set; }

    public Guid UserId { get; set; }

    public Guid? StationId { get; set; }

    public string EmployeeCode { get; set; }

    public DateOnly HireDate { get; set; }

    public string Position { get; set; }

    public virtual ICollection<Swap> Swaps { get; set; } = new List<Swap>();
}